name: Build Geomatic Pro

on:
  workflow_dispatch:

  push:
    paths:
      - '**/*.html'
      - '**/*.jpg'
      - '**/*.png'
      - '.github/workflows/build-apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # ==============================
      # 1. دریافت پروژه
      # ==============================
      - name: Checkout
        uses: actions/checkout@v4


      # ==============================
      # 2. Java 17
      # ==============================
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'


      # ==============================
      # 3. Gradle
      # ==============================
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'


      # ==============================
      # 4. ساخت پوشه‌های Android
      # ==============================
      - name: Create Android project
        run: |

          mkdir -p app/src/main/java/com/miladgeo/app
          mkdir -p app/src/main/assets
          mkdir -p app/src/main/res/drawable


          # ==================================
          # نسخه چندزبانه برنامه
          # ==================================

          cp index109_multilang.html \
             app/src/main/assets/index.html


          # ==================================
          # آیکون برنامه
          # ==================================

          cp miladgeo-icon.jpg \
             app/src/main/res/drawable/milad
